name: app

services:
  application:
    container_name: application
    build: ./
    ports:
      - "8080:8080"
    environment:
      JWT_TTL: 900
      JWT_SECRET: supersecret
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_started

  db:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: jwt
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  migrate:
    container_name: migration
    image: migrate/migrate
    volumes:
      - ./schema:/schema
    command: [ "-path", "/schema", "-database",  "postgres://postgres:1234@db:5432/jwt?sslmode=disable", "up" ]
    depends_on:
      db:
        condition: service_healthy